openapi: "3.0.2"
info:
  title: OpenApi
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://localhost:4000
    description: Localhost server

paths:
  # USERS
  /users:
    post:
      summary: User register.
      description: Allow to register a new user with Username, Email and Password.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                  - email
                  - password
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string

      responses:
        "200":
          description: Everything Ok
        "400":
          description: Bad Request
        "404":
          description: Invalid Path
  # LOGIN
  /users/login:
    post:
      summary: User login.
      description: Allow to login a user with the Email and Password.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                password:
                  type: string

      responses:
        "200":
          description: Everything Ok
        "400":
          description: Bad Request
        "404":
          description: Invalid Path

  #  EDIT USER
  /users/edit:
    put:
      description: ""
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                email: # <!--- form field name
                  type: string
                bio: # <!--- form field name
                  type: string

        #  ANHADIR FOTO

      responses:
        "200":
          description: OK
